### ISSUE TITLE
[feature] Inserir uma sessão para E-books

### ISSUE THREAD

**Issue by cristofersousa** [leonardorifeli/caboclopenabranca.github.io#1]
**Objetivo:**

Adicionar no menu uma sessão para apostilas/ebooks.

**Intenção:**

Propagar e deixar público o acesso a materiais criados pelo centro.

**Comment by leonardorifeli** [comment]
Muito show! Só não podemos colocar os ebooks que compramos pro centro. Acho que podemos reescrever o conteúdo com base em nossa tradição.
