### ISSUE TITLE
[feature] Adicionar uma sessão de Contabilidade

### ISSUE THREAD

**Issue by cristofersousa** [leonardorifeli/caboclopenabranca.github.io#4]
**Objetivo** 

Colocar uma sessão para contabilidade, livro caixa.

**Motivo**

Ficará público todas as despesas e receita que a casa possui, dessa forma acredito que fica transparente todo o fluxo de caixa do centro.

**Comment by leonardorifeli** [comment]
Achei bem foda! Vamos só estudar se por agora é melhor deixarmos só no centro essa info, nos murais e tal, e depois quando virarmos associação deixaremos tudo realmente público.
